version: "3"
services:
  web:
    build: ./
    depends_on:
      - redis

  redis:
    image: redis
    command: ["redis-server", "--bind", "redis", "--port", "6379"]

  nginx:
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web